Add another Growlab technician
alexellis/growlab pull request #40
Opened 2021-05-24 19:54 UTC by mtaylorsherwood

Add me in as a new technician for the project and apply bronze level.

Also fixes a small typo in the readme.

2021-05-25 15:22 UTC, alexellis commented
Thanks for the interest. I've added a note.

We will also need this for the data logger. Don't worry that it's duplicated.

Alex

2021-05-25 15:22 UTC, alexellis requested changes
Submitting a review

2021-05-25 15:22 UTC, alexellis commented on app/app.py
> +        sensor = growbme680(config["sensors"]["oversample"])
Let's just have that as the default and make it less complicated?

2021-05-25 15:50 UTC, mtaylorsherwood commented
Thanks for the feedback. Have added the sensor to the data logger as well as removing that config option for simplicity.

2021-06-07 16:35 UTC, alexellis commented
@pensarguet can you take a look and compare to your own patch?

2021-06-07 17:05 UTC, mtaylorsherwood commented
> @pensarguet can you take a look and compare to your own patch?

I'm happy to refractor mine and tidy it up once their PR is merged in, to be honest thr history is a bit messy now

2021-06-07 20:01 UTC, pensarguet commented
Hi Alex, 

The code from Martyn is more complete than mine and embed the data logger and the calibration stage before getting the value.
For the logic, it's similar ;-)

2021-06-25 11:23 UTC, mtaylorsherwood commented
Closing so other PR's can be done and I can rebase

2021-06-25 11:23 UTC, closed without merging